### ISSUE TITLE
vuex getter properties are read-only.

### ISSUE THREAD

**Issue by kevinlelelily** [Yuyz0112/vue-notie#2]
自动关闭设置为true，定时结束后控制台会出现这个错误

**Comment by Yuyz0112** [comment]
@kevinlelelily 
可以看看结合vuex使用的方法：https://segmentfault.com/a/1190000005932457#articleHeader8
注意如果用vuex的话，要把组件内的close方法替换成actions中暴露的对应方法。

**Comment by kevinlelelily** [comment]
@Yuyz0112 好的，这个问题解决了谢谢。是我遗漏了，vuex中规定“组件不允许直接修改 store 实例的状态”
